### ISSUE TITLE
Cancel the drop event

### ISSUE THREAD

**Issue by gazpachu** [dabeng/OrgChart#304]
I've tried to continue the conversation on #31, but no one is answering. Maybe because the issue is closed?

AFAIK, the dropcriteria only works to allow or deny the drop, but what if we want to cancel the drop once it happened?

I'm asking because I'm showing a confirm modal dialog after the drop and I only want to accept the drop if the user click's on accept. If the user clicks on cancel then the drop wouldn't happen.

I've tried with event.stopPropagation() and event.preventDefault() but they don't cancel the drop. I've also tried with the dragend.orgchart event but it doesn't cancel the drag either.

Is there any other event I can use? like beforeNodeDropped?

Thanks

**Comment by dabeng** [comment]
Hi @gazpachu , just now I released orgchart version 2.0.9, it allows users to add cancel the drop node action if users perform `event.preventDefault()` within "nodedrop.orgchart" event handler. Thank you very much for committing this bug 😊 . 

I create a demo on codepen.io for you. Hope you like it -- [Add custom validation for orgchart drag&drop](https://codepen.io/dabeng/pen/vWrmvg?editors=0110).

Besides, you said that your business logic involves a **confirm modal dialog**, I created a popup repo named [Simple-Popup](https://github.com/dabeng/Simple-Popup) long ago and hope it would be a viable option for you.

**Comment by gazpachu** [comment]
Many thanks @dabeng! I still can't install 2.0.9 from NPM, only up to 2.0.7

**Comment by dabeng** [comment]
Hi @gazpachu , it's just some kind of delay.

**Comment by gazpachu** [comment]
Thanks, it works like a charm :)
